add_rules("mode.debug", "mode.release")
set_languages("c17")

set_warnings("allextra")
set_policy("build.sanitizer.address", true)
set_policy("build.sanitizer.undefined", true)
set_policy("run.autobuild", true)
add_cflags("-Wno-unused-label")

package("sdl3")
    add_deps("cmake")
    add_links("SDL3")
    set_sourcedir(path.join(os.scriptdir(), "thirdparty", "SDL"))
    on_install(function (package)
        local configs = {}
        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
        table.insert(configs, "-DBUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
        import("package.tools.cmake").install(package, configs)
    end)
    on_test(function (package)
        assert(package:has_cincludes("SDL3/SDL.h"))
    end)
package_end()

add_requires("unity_test ^2")
add_requires("sdl3", {configs = {shared = false}})
add_requires("vulkansdk", {configs = {utils = {"volk"}}})
add_requires("nuklear")
add_requires("openmp")

target("msc")
    set_kind("static")
    add_includedirs("libmsc/src")
    add_files("libmsc/src/*.c")
    add_includedirs("libmsc/include", {public = true})
    add_headerfiles("libmsc/include/*.h")

target("main")
    set_kind("binary")
    add_rules("utils.glsl2spv", {bin2c = true})
    add_files("shaders/**/*.vert", "shaders/**/*.frag")
    set_pcheader("src/stdafx.h")
    add_includedirs("src")
    add_files("src/main.c", "src/**/*.c")
    add_deps("msc")
    add_packages("sdl3")
    add_packages("vulkansdk")
    add_packages("nuklear")
    add_packages("openmp")